config/routes.rb
Trailsyserver::Application.routes.draw do
  resources :organizations

  devise_for :users, :controllers => { :registrations => "registrations" }
  
  scope "/admin" do
    resources :users do
      member do
        get :approve
      end
    end
  end
  
  resources :trailsegments do
    collection do
      post 'upload'
    end
  end

  resources :trailheads do
    collection do
      post 'upload'
    end
  end

  resources :trails do
    collection do
      post 'upload'
    end
  end

  get '.well-known/status' => 'status#check'

  get '/admin' => 'trails#index'
  
  root 'trails#index'

  

end

app/models/trailsegment.rb
class Trailsegment < ActiveRecord::Base
  set_rgeo_factory_for_column(:geom, RGeo::Geographic.spherical_factory(:srid => 4326))
  validates_uniqueness_of :geom

  validates :source, presence: true
  validates :steward, presence: true
  validates :geom, presence: true

  belongs_to :steward, class_name: 'Organization', foreign_key: "steward_id"
  belongs_to :source, class_name: 'Organization', foreign_key: "source_id"

  def self.parse_geojson(file)
    logger.info file.class
    if file.class == ActionDispatch::Http::UploadedFile
      feature_collection = RGeo::GeoJSON.decode(File.read(file.path), json_parser: :json)
    elsif file.class == String
      feature_collection = RGeo::GeoJSON.decode(File.new(file), json_parser: :json)
    elsif file.class == File
      feature_collection = RGeo::GeoJSON.decode(file, json_parser: :json)
    end
    parsed_trailsegments = []
    feature_collection.each do |feature|
      new_trailsegment = Trailsegment.new
      feature.properties.each do |property|
        key = property[0].downcase
        value = property[1]
        next if key == "id" || value == "" || value == " "
        unless value.nil?
          if value.to_s.downcase == "yes" || value == "Y"
            value = "y"
          end
          if value.to_s.downcase == "no" || value == "N"
            value = "n"
          end
        end
        if new_trailsegment.attributes.has_key? key
          new_trailsegment[key] = value
        elsif key == "source"
          new_trailsegment.source = Organization.find_by code: value
        elsif key == "steward"
          new_trailsegment.steward = Organization.find_by code: value
        end
      end
      new_trailsegment["geom"] = feature.geometry
      if new_trailsegment.steward.nil?
        new_trailsegment.steward = new_trailsegment.source
      end
      parsed_trailsegments.push new_trailsegment
    end
    parsed_trailsegments
  end

  def self.parse_shapefile(file) 
    shapefile_parts = []
    shapefile_directory = "#{Rails.root.to_s}/tmp/#{file.original_filename}"
    Zip::File.open(file.path) do |zip|
      zip.each do |entry|
        shapefile_parts.push(entry.name)
        FileUtils.mkdir_p(shapefile_directory)
        filename =  "#{shapefile_directory}/#{entry.name}"
        zip.extract(entry, filename) { true }
      end
    end
    shp_name = shapefile_parts[shapefile_parts.index { |name| name =~ /.shp$/}]
    json_name = shp_name.sub(/.shp$/, ".4326.geojson")

    shp_path = "#{shapefile_directory}/#{shp_name}"
    json_path = "#{shapefile_directory}/#{json_name}"
    File.delete(json_path) if FileTest.exist?(json_path)
    prj_path = shp_path.sub(/.shp$/, ".prj")
    # hack here because MPSSC shapefiles don't include projections

    s_srs_string = FileTest.exist?(prj_path) ? "" : "-s_srs EPSG:3734"

    cmd = %Q(#{ENV['GDAL_BINDIR']}/ogr2ogr -f "GeoJSON" \
             -t_srs EPSG:4326 \
             #{s_srs_string} \
             #{json_path} \
             #{shp_path} \
             -nlt PROMOTE_TO_MULTI)

    logger.info `#{cmd}`

    return self.parse_geojson(File.new("#{json_path}", "r")) 
  end

  def self.parse(file) 
    if (file.original_filename =~ /zip$/)
      return self.parse_shapefile(file)
    elsif (file.original_filename =~ /json$/)
      return self.parse_geojson(file)
    end
  end

  def merged_geom=(geom)
    @merged_geom = geom
  end

  def merged_geom
    @merged_geom
  end
  # def self.source_trailsegments(trailsegments, source) 
  #   trailsegments.select { |trailsegment| trailsegment.source.code == source }
  # end

  # def self.non_source_trailsegments(trailsegments, source) 
  #   trailsegments.select { |trailsegment| trailsegment.source.code != source }
  # end
end

app/controllers/trailsegments_controller.rb
class TrailsegmentsController < ApplicationController
  before_action :set_trailsegment, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_show_all_param
  before_action :check_for_cancel, only: [:update]
  
  # GET /trailsegments
  # GET /trailsegments.json
  # if "simplify" number parameter is supplied, get the ST_LineMerge version of the segment geometries, then
  # simplify all of the resulting LineStrings to include the first point, the last point, 
  # and every "simplify"th point in between. 
  # An attempt to simplify the data enough for Leaflet to work on iOS 7 MobileSafari.

  def index

    respond_to do |format|
      format.html do
        authenticate_user!
        if params[:all] == "true" || current_user.admin?
          @trailsegments = Trailsegment.order("trail1").order("trail2").order("trail3")
        else
          @trailsegments = Trailsegment.joins(:source).merge(Organization.where(id: current_user.organization)).order("trail1").order("trail2").order("trail3")
        end
      end
      format.json do
        trailID = params[:trail_id]
        simplify_factor = params[:simplify].to_i
        if simplify_factor > 0
          @trailsegments = Trailsegment.find_by_sql(["select *, st_linemerge(geom::geometry) as merged_geom from trailsegments"]);
        else
          if trailID
            trail_name = Trail.find(trailID).name
            @trailsegments = Trailsegment.where("trail1 = ? 
              OR trail2 = ? 
              OR trail3 = ?
              OR trail4 = ?
              OR trail5 = ?
              OR trail6 = ?", trail_name, trail_name, trail_name, trail_name, trail_name, trail_name)
          else
            @trailsegments = Trailsegment.all
          end
        end


        @entity_factory = ::RGeo::GeoJSON::EntityFactory.instance
        line_factory = ::RGeo::Geographic.spherical_factory(:srid => 4326)
        features = []

        @trailsegments.each do |trailsegment|
          merged_geom = trailsegment.attributes["merged_geom"]
          if simplify_factor > 0
            if merged_geom.geometry_type.type_name == "MultiLineString" # for multilinestrings we need to loop through contained linestrings
              new_trailsegment_linestrings = []
              merged_geom.each_with_index do |linestring, ls_index|
                new_linestring_points = []
                linestring.points.each_with_index do |point, p_index| # and then loop through the points in each linestring
                  if p_index % simplify_factor == 0 || p_index == linestring.num_points - 1
                    new_linestring_points.push(point)
                  end
                end
                new_trailsegment_linestrings.push(line_factory.line_string(new_linestring_points))
              end
              simplified_trailsegment_geom = line_factory.multi_line_string(new_trailsegment_linestrings)
              trailsegment.geom = simplified_trailsegment_geom

            elsif merged_geom.geometry_type.type_name == "LineString" # for linestrings we can just loop through the points
              new_linestring_points = []
              merged_geom.points.each_with_index do |point, p_index|
                if p_index % simplify_factor == 0 || p_index == merged_geom.num_points() - 1
                  new_linestring_points.push(point)
                end
              end
              simplified_trailsegment_geom = line_factory.line_string(new_linestring_points)
              trailsegment.geom = simplified_trailsegment_geom
            end
          end
          json_attributes = create_json_attributes(trailsegment)
          feature = @entity_factory.feature(trailsegment.geom, 
            trailsegment.id, 
            json_attributes)
          features.push(feature)
        end
        collection = @entity_factory.feature_collection(features)
        my_geojson = RGeo::GeoJSON::encode(collection)
        render json: Oj.dump(my_geojson)
      end
    end
  end

  # GET /trailsegments/1
  # GET /trailsegments/1.json
  def show
    respond_to do |format|
      format.html
      format.json do
        @entity_factory = ::RGeo::GeoJSON::EntityFactory.instance
        json_attributes = create_json_attributes(@trailsegment)
        feature = @entity_factory.feature(@trailsegment.geom, @trailsegment.id, json_attributes )
        render json: RGeo::GeoJSON::encode(feature)
      end
    end
  end

  # GET /trailsegments/new
  # def new
  #   @trailsegment = Trailsegment.new
  # end

  # GET /trailsegments/1/edit
  def edit
    unless authorized?
      redirect_to trailsegments_path, notice: 'Authorization failure.'
    end
  end

  # # POST /trailsegments
  # # POST /trailsegments.json
  # def create
  #   @trailsegment = Trailsegment.new(trailsegment_params)

  #   respond_to do |format|
  #     if @trailsegment.save
  #       format.html { redirect_to trailsegments_path, notice: 'Trail segment was successfully created.' }
  #       format.json { render action: 'show', status: :created, location: @trailsegment }
  #     else
  #       format.html { render action: 'new' }
  #       format.json { render json: @trailsegment.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /trailsegments/1
  # PATCH/PUT /trailsegments/1.json
  def update
    respond_to do |format|
      if authorized? && @trailsegment.update(trailsegment_params)
        format.html { redirect_to trailsegments_path, notice: 'Trailsegment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @trailsegment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trailsegments/1
  # DELETE /trailsegments/1.json
  def destroy
    respond_to do |format|
      if authorized? && @trailsegment.destroy
        format.html { redirect_to trailsegments_url, notice: "Trail segment was successfully deleted." }
        format.json { render :json => { head: :no_content }, status: :ok }
      else
        format.html { redirect_to trailsegments_url, notice: "Trail segment was not deleted."}
        format.json { render :json => { head: :no_content }, status: :unprocessable_entity }
      end
    end
  end

  def upload
    if !current_user
      head 403
    end
    @confirmed = params[:confirmed] ? true : false
    redirect_to trailsegments_url, notice: "Please enter a source organization code for uploading trail segment data." if params[:source_id].empty?
    source_id = params[:source_id]
    @source = Organization.find(source_id)
    parsed_trailsegments = Trailsegment.parse(params[:trailsegments])
    if parsed_trailsegments.nil?
      redirect_to trailsegments_url, notice: "Unable to parse file #{params[:trailsegments].orginial_filename}. Make sure it is a valid GeoJSON file or zipped shapefile."
      return
    end
    source_trailsegments = Trailsegment.where(source: @source)
    @non_source_trailsegments = Trailsegment.where.not(source: @source)
    @removed_trailsegments = []
    source_trailsegments.each do |old_trailsegment|
      removed_trailsegment = Hash.new
      removed_trailsegment[:trailsegment] = old_trailsegment
      if @confirmed
        removed_trailsegment[:success] = old_trailsegment.destroy
      else
        removed_trailsegment[:success] = true
      end
      @removed_trailsegments.push(removed_trailsegment)
    end
    @added_trailsegments = []
    parsed_trailsegments.each do |new_trailsegment|
      added_trailsegment = Hash.new
      added_trailsegment[:trailsegment] = new_trailsegment
      if new_trailsegment.source != @source
        added_trailsegment[:success] = false
        if !new_trailsegment.source.nil?
          added_trailsegment[:message] = "Trail segment organization #{new_trailsegment.source.code} doesn't match user organization #{@source.code}."
        else
          added_trailsegment[:message] = "No trail segment source found."
        end
      elsif @confirmed
        if (new_trailsegment.save)
          added_trailsegment[:success] = true
        else
          added_trailsegment[:success] = false
          added_trailsegment[:message] = new_trailsegment.errors.full_messages
        end
      else
        if (new_trailsegment.valid?)
          added_trailsegment[:success] = true
        else
          if new_trailsegment.errors.full_messages == ["Geom has already been taken"]
            added_trailsegment[:success] = true
          else
            added_trailsegment[:success] = false
            added_trailsegment[:message] = new_trailsegment.errors.full_messages
          end
        end
      end
      @added_trailsegments.push(added_trailsegment)
    end
  end

  def default_url_options
    { all: @show_all }.merge(super)
  end

  def set_show_all_param
    @show_all = params[:all] if params[:all]
  end

  def create_json_attributes(trailsegment)
    json_attributes = trailsegment.attributes.except("geom", "wkt", "created_at", "updated_at")
    if trailsegment.source
      json_attributes["source"] = trailsegment.source.code
      json_attributes["source_fullname"] = trailsegment.source.full_name
      json_attributes["source_phone"] = trailsegment.source.phone
      json_attributes["source_url"] = trailsegment.source.url
    end
    if trailsegment.steward
      json_attributes["steward"] = trailsegment.steward.code
      json_attributes["steward_fullname"] = trailsegment.steward.full_name
      json_attributes["steward_phone"] = trailsegment.steward.phone
      json_attributes["steward_url"] = trailsegment.steward.url
    end
    json_attributes
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trailsegment
      @trailsegment = Trailsegment.find(params[:id])
    end

    def authorized?
      (current_user.organization == @trailsegment.source || current_user.admin?)
    end

app/helpers/trailsegments_helper.rb
module TrailsegmentsHelper
end

app/views/trailsegments/_form.html.erb
<%= form_for(@trailsegment) do |f| %>
  <% if @trailsegment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trailsegment.errors.count, "error") %> prohibited this trailsegment from being saved:</h2>

      <ul>
      <% @trailsegment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <span class='h3-Edit'><%= f.label :source %></span>
    <span class='finePrint'> This is the organization who uploaded the info.</span>
    <span class='formAnswer'><%= @trailsegment.source.code %></span>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :steward %></span>
    <span class='finePrint'>This is the organization the park visitor should contanct for more information. </span>
    <span class='formAnswer'><%= f.select :steward_id, Organization.all.collect{ |org| [org.code, org.id]} %></span>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :length %></span>
    <span class='finePrint'>Note: This number is automatically rounded to the first decimal point in the user-facing application.</span>
    <%= f.text_field :length %>
    <span class='formAnswer'>miles</span>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :trail1 %></span>
    <%= f.text_field :trail1, size: 80 %>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :trail2 %></span>
    <%= f.text_field :trail2, size: 80 %>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :trail3 %></span>
    <%= f.text_field :trail3, size: 80 %>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :trail4 %></span>
    <%= f.text_field :trail4, size: 80 %>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :trail5 %></span>
    <%= f.text_field :trail5, size: 80 %>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :trail6 %></span>
    <%= f.text_field :trail6, size: 80 %>
  </div>
  
  <br>
  <div class='finePrint'>The following y/n fields are not currently being used in the user-facing app. Feel free to input this information for future use.</div>

  <div class="field">
    <span class='h3-Edit'><%= f.label :accessible, "Accessible" %></span>
    <%= f.select :accessible, ["y", "n"], {include_blank: true} %>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :hike, "Hiking" %></span>
    <%= f.select :hike, ["y", "n"], {include_blank: true} %>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :equestrian %></span>
    <%= f.select :equestrian, ["y", "n"], {include_blank: true} %>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :xcntryski, "Cross-Country Ski" %></span>
    <%= f.select :xcntryski, ["y", "n"], {include_blank: true} %>
  </div>
  <!-- We aren't displaying this in trailsy, so hiding it here 
  <div class="field">
    <span class='h3-Edit'><%= f.label :dogs %></span>
    <%= f.select :dogs, ["y", "n"], {include_blank: true} %>
  </div> -->
  <div class="field">
    <span class='h3-Edit'><%= f.label :roadbike, "Road Bikes" %></span>
    <%= f.select :roadbike, ["y", "n"], {include_blank: true} %>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :mtnbike, "Mountain Bikes" %></span>
    <span class='finePrint'>This field has been manually disabled in the user-facing app (the button is gray). If you select "y" get in touch with the admin so that the html/css can be updated and users can begin filtering for mountain bikes.</span>
    <%= f.select :mtnbike, ["y", "n"], {include_blank: true} %>
  </div>


  <div class="actions">
    <%= f.submit %>
    <%= f.submit :Cancel %>
  </div>
<% end %>

app/views/trailsegments/edit.html.erb
<h1>Edit Trail Segment</h1>

<div class='formContent'>
	<%= render 'form' %>
</div>

<div class='formButtons'>
	<!--back button <span class='backButton'>	
		<%= link_to 'Back', trailsegments_path %>
	</span> -->
	<span class='addNewButton'>	
		<%= link_to 'View', @trailsegment %>
	</span>	
 </div>

app/views/trailsegments/index.html.erb
<h1>Segment List</h1>
<p class='uploadDescription'>
Upload a GeoJSON file or shapefile (all shapefile component files collected into a single .zip file) of your current trail segment data to update this list (make sure it follows the <a href="https://docs.google.com/a/codeforamerica.org/document/d/1frt5HkKTdqEaNEnfk2Dq9IYxctvPjVnoU_F33Px2zSQ/edit" target="_blank">standard</a>). Note: this will replace all of your organization's existing data! Before replacing content, we recommend downloading your current data in case anything goes wrong. You can download the current trail segment data for 
<% if current_user.admin? %>
  <%= link_to "all sources", {action: "index", format: :json}, target: "_blank" %>
  <% else %>
  <%= link_to "#{current_user.organization.code}", {action: "index", source_id: current_user.organization_id, format: :json}, target: "_blank" %>    
  <% end %>
  here.
</p>

<%= form_tag({ action: :upload }, multipart: true) do %>
  <% if current_user.admin? %>
  <%= select_tag "source_id", options_from_collection_for_select(Organization.all, :id, :code) %>
  <% else %>
  <%= hidden_field_tag 'source_id', current_user.organization.id %>
  <% end %>
  <%= file_field_tag 'trailsegments' %><br>

 <%= submit_tag "Test Upload", id: "submitData", data: { confirm: 'Are you sure? If the "Replace Existing Data" box is checked, this will replace all of your existing trail data.' } %>
  <%= label_tag :confirmed, 'Replace Existing Data' %>
  <%= check_box_tag 'confirmed', 'Confirm', false, {id: "confirmed", onclick: "if ($('#confirmed').is(':checked')) { $('#submitData').val('Upload Data') } else {  $('#submitData').val('Test Upload'); }"} %> 
<% end %>
<br>
<% if current_user.admin? %>
<p class='tableCaption'>
Showing all trail segments.
</p>
<% else %>
<span class='tabLeft <%= "active" if params[:all] == "true" %>'><%= link_to "All Segments", :action => "index", :all => "true" %></span>
<span class='tabRight <%= "active" if params[:all] == "false" || params[:all].nil? %>'><%= link_to "Only #{current_user.organization.code} Segments", :action => "index", :all => "false" %></span>
<% end %>
<table>
  <thead>
    <tr>
      <th>Length</th>
      <th>Source</th>
      <th>Steward</th>
      <th>Trails</th>
      <th colspan=3>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @trailsegments.each do |trailsegment| %>
    <tr>
      <td><%= trailsegment.length %></td>
      <td><%= trailsegment.source.code if trailsegment.source %></td>
      <td><%= trailsegment.steward.code if trailsegment.steward %></td>
      <td>
        <ul>
          <% %w[trail1 trail2 trail3 trail4 trail5 trail6].each do |trail| %>
          <% if !(trailsegment["#{trail}"].nil?) && trailsegment["#{trail}"].size > 0 %>
          <li><%= trailsegment["#{trail}"] %></li>
          <% end %>
          <% end %>
        </ul>
      </td>
      <% if (current_user.admin? || current_user.organization == trailsegment.source) %>
      <td><%= link_to 'View', trailsegment, :class => "tableLink" %></td>
      <td><%= link_to 'Edit', edit_trailsegment_path(trailsegment), :class => "tableLink" %></td>
      <td><%= link_to 'Delete', trailsegment, :class => "tableLink-delete", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/trailsegments/new.html.erb
<h1>New trailsegment</h1>

<%= render 'form' %>

<%= link_to 'Back', trailsegments_path %>

app/views/trailsegments/show.html.erb
<p id="notice"><%= notice %></p>

<div class='formContent-Show'>
  <h3>
    Length:
    <span class='formAnswer'><%= @trailsegment.length %></span>
  </h3>

  <h3>
    Source:
    <span class='formAnswer'><%= @trailsegment.source.code %></span>
  </h3>

  <h3>
    Steward:
    <span class='formAnswer'><%= @trailsegment.steward.code %></span>
  </h3>

  <h3>
    Trail1:
    <span class='formAnswer'><%= @trailsegment.trail1 %></span>
  </h3>

  <h3>
    Trail2:
    <span class='formAnswer'><%= @trailsegment.trail2 %></span>
  </h3>

  <h3>
    Trail3:
    <span class='formAnswer'><%= @trailsegment.trail3 %></span>
  </h3>

  <h3>
    Trail4:
    <span class='formAnswer'><%= @trailsegment.trail4 %></span>
  </h3>

  <h3>
    Trail5:
    <span class='formAnswer'><%= @trailsegment.trail5 %></span>
  </h3>

  <h3>
    Trail6:
    <span class='formAnswer'><%= @trailsegment.trail6 %></span>
  </h3>

  <h3>
    Geometry: 
    <span class='formAnswer'><%= @trailsegment.geom %></span>
  </h3>
</div>

<div class='formButtons'>
  <!--back button <span class='backButton'>
    <%= link_to 'Back', trailsegments_path %>
  </span> -->
  <span class='addNewButton'>
    <%= link_to 'Edit', edit_trailsegment_path(@trailsegment) %>
  </span>
</div>

app/views/trailsegments/upload.html.erb
<!-- TODO: consider merging this with other upload views -->
<h1>Trail Segment Upload Complete</h1>
<p>Note: See the table below for specific information regarding the upload for each trail segment listing.</p> 
<p>Errors are featured within the table.</p>
<!--<%= link_to "Back to Trailsegment Listing", trailsegments_path %>-->
<p class='tableCaption'>Source matches (matching "<%= @source.code %>")</p>

<table>
  <tr>
    <th>
      Status
    </th>
    <th>
      Trailsegment Name
    </th>
    <th>
      Import errors
    </th>
  </tr>
  <% @added_trailsegments.each do |added_trailsegment| %>
  <tr>
    <td>
      <% if added_trailsegment[:success] %>
      <b><%= @confirmed ? "Added" : "Would Be Added" %></b>
      <% else %>
      <b><%= @confirmed ? "Not Added" : "Would Not Be Added" %></b> 
      <% end %>
    </td>
    <td>
      <% segment_list = [added_trailsegment[:trailsegment].trail1,
      added_trailsegment[:trailsegment].trail2,
      added_trailsegment[:trailsegment].trail3,
      added_trailsegment[:trailsegment].trail4,
      added_trailsegment[:trailsegment].trail5,
      added_trailsegment[:trailsegment].trail6].reject!(&:blank?) %>
      <%= segment_list.join("|") unless segment_list.nil? %>
    </td>
    <td>
      <%= added_trailsegment[:message] %>
    </td>
  </tr>
  <% end %>
  <% @removed_trailsegments.each do |removed_trailsegment| %>
  <tr>
    <td>  
      <% if removed_trailsegment[:success] %>
      <b><%= @confirmed ? "Deleted" : "Would Be Deleted" %></b>  
      <% else %>
      <b><%= @confirmed ? "Not Deleted" : "Would Not Be Deleted" %></b>
      <% end %>
    </td>
    <td>
      <% segment_list = [removed_trailsegment[:trailsegment].trail1,
      removed_trailsegment[:trailsegment].trail2,
      removed_trailsegment[:trailsegment].trail3,
      removed_trailsegment[:trailsegment].trail4,
      removed_trailsegment[:trailsegment].trail5,
      removed_trailsegment[:trailsegment].trail6].reject!(&:blank?) %>
      <%= segment_list.join("|") unless segment_list.nil? %>
    </td>
    <td>
      <%= removed_trailsegment[:trailsegment].created_at %>
    </td>
  </tr>
  <% end %>
</table>
<!-- 
<h3>Source non-matches (should be "<%= @source.code %>")</h3>
<table>
  <tr>
    <th>Trailsegment name</th>
    <th>Source field in Upload</th>
  </tr>
<% @non_source_trailsegments.each do |trailsegment| %>
  <tr>
    <td>
      <%= trailsegment.trail1 %>|
      <%= trailsegment.trail2 %>|
      <%= trailsegment.trail3 %>|
      <%= trailsegment.trail4 %>|
      <%= trailsegment.trail5 %>|
      <%= trailsegment.trail6 %>
    </td>
    <td>
      <%= trailsegment.source.code %>
    </td>
  </tr>
<% end %>
</table>
-->