config/routes.rb
Trailsyserver::Application.routes.draw do
  resources :organizations

  devise_for :users, :controllers => { :registrations => "registrations" }
  
  scope "/admin" do
    resources :users do
      member do
        get :approve
      end
    end
  end
  
  resources :trailsegments do
    collection do
      post 'upload'
    end
  end

  resources :trailheads do
    collection do
      post 'upload'
    end
  end

  resources :trails do
    collection do
      post 'upload'
    end
  end

  get '.well-known/status' => 'status#check'

  get '/admin' => 'trails#index'
  
  root 'trails#index'

  

end

app/models/trail.rb
class Trail < ActiveRecord::Base

  attr_accessor :delete_photo

  validates :name, uniqueness: { scope: :source, message: " has already been taken for this source"}
  validates :source, presence: true
  validates :steward, presence: true
  has_one :photorecord, dependent: :nullify

  belongs_to :steward, class_name: 'Organization', foreign_key: "steward_id"
  belongs_to :source, class_name: 'Organization', foreign_key: "source_id"

  accepts_nested_attributes_for :photorecord, allow_destroy: true


  def self.parse_csv(file)
    parsed_trails = []
    if file.class == ActionDispatch::Http::UploadedFile
      file_ident = file.path
    else
      file_ident = file
    end

    # if the encoding is bad, assume windows-1252
    
    contents = File.read(file_ident)
    unless contents.valid_encoding?
      contents.encode!("utf-8", "windows-1252", :invalid => :replace)
    end

    CSV.parse(contents, headers: true, header_converters: :downcase) do |row|
      new_trail = Trail.new
      next if (row.to_s =~ /^source/)

      row.headers.each do |header|
        value = row[header]
        next if header == "id"
        unless value.nil?
          if value.to_s.downcase == "yes" || value == "Y"
            value = "y"
          end
          if value.to_s.downcase == "no" || value == "N"
            value = "n"
          end
        end
        # next if header == "source"
        if new_trail.attributes.has_key? header
          new_trail[header] = value
        elsif header == "source"
          new_trail.source = Organization.find_by code: value
        elsif header == "steward"
          new_trail.steward = Organization.find_by code: value
        end
      end
      parsed_trails.push new_trail
    end
    parsed_trails
  end

  def self.parse_json(file)
    parsed_trails = []
    if file.class == ActionDispatch::Http::UploadedFile
      trails_input = JSON.parse(file.read)
    else
      trails_input = JSON.parse(File.new(file).readlines.join("\n"))
    end
    trails_input["features"].each do |feature|
      new_trail = Trail.new
      properties = feature["properties"]
      properties.each do |fieldname, fieldvalue|
        next if fieldname == "id"
        unless fieldvalue.nil?
          if fieldvalue.to_s.downcase == "yes" || fieldvalue == "Y"
            fieldvalue = "y"
          end
          if fieldvalue.to_s.downcase == "no" || fieldvalue == "N"
            fieldvalue = "n"
          end
        end
        # next if fieldname == "source"
        if new_trail.attributes.has_key? fieldname
          logger.info fieldname
          logger.info fieldvalue
          new_trail[fieldname] = fieldvalue
        elsif fieldname == 'source'
         new_trail.source = Organization.find_by code: fieldvalue
        elsif fieldname == 'steward'
          new_trail.steward = Organization.find_by code: fieldvalue
        end
      end
      parsed_trails.push new_trail
    end
    parsed_trails
  end

  def self.parse(file)
    if (file.original_filename =~ /csv$/)
      return self.parse_csv(file)
    elsif (file.original_filename =~ /json$/)
      return self.parse_json(file)
    else
      nil
    end
  end
  
  def self.to_csv
    CSV.generate do |csv|
      headers = column_names
      headers.each_index do |index|
        if headers[index] == "source_id"
          headers[index] = "source"
        end
        if headers[index] == "steward_id"
          headers[index] = "steward"
        end
      end
      csv << headers
      all.each do |trail|
        row_ary = []
        headers.each do |header|
          if header == "source"
            row_ary.push trail.source.code
          elsif header == "steward"
            row_ary.push trail.steward.code
          else
            row_ary.push trail.read_attribute("#{header}")
          end
        end
        csv << row_ary
      end
    end
  end
end

app/controllers/trails_controller.rb
class TrailsController < ApplicationController
  before_action :set_trail, only: [:show, :edit, :destroy, :update]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_show_all_param
  before_action :check_for_cancel, only: [:update]

  # GET /trails
  # GET /trails.json
  def index    
    respond_to do |format|
      format.html do
        authenticate_user!
        if !user_signed_in? || (!current_user.admin && current_user.organization.nil?)
          sign_out :user
          redirect_to trails_path
          return  
        end
        if @show_all == "true" || current_user.admin?
          @trails = Trail.all.includes([:photorecord]).order("name")
        else
          # @trails = Trail.where(source: current_user.organization).order("name")
          @trails = Trail.includes([:photorecord]).joins(:source).merge(Organization.where(id: current_user.organization)).order("name")
        end
      end
      format.json do
        if params[:source_id].nil?
          @trails = Trail.includes([:photorecord]).order("name")
        else
          @trails = Trail.includes([:photorecord]).where(source_id: params[:source_id]).order("name")
        end
        entity_factory = ::RGeo::GeoJSON::EntityFactory.instance
        features = []
        @trails.each do |trail|
          # taking a trip to Null Island, because RGeo::GeoJSON chokes on empty geometry here
          json_attributes = create_json_attributes(trail)
          feature = entity_factory.feature(RGeo::Geographic.spherical_factory.point(0,0), trail.id, json_attributes)
          features.push(feature)
        end
        collection = entity_factory.feature_collection(features)
        my_geojson = RGeo::GeoJSON::encode(collection)
        render json: Oj.dump(my_geojson)
      end
      format.csv do
        if params[:source_id].nil?
          @trails = Trail.includes([:photorecord]).order("name")
        else
          @trails = Trail.includes([:photorecord]).where(source_id: params[:source_id]).order("name")
        end
        render text: @trails.to_csv
      end
    end
  end

  # GET /trails/1
  # GET /trails/1.json
  def show
    respond_to do |format|
      format.html 
      format.json do
        entity_factory = ::RGeo::GeoJSON::EntityFactory.instance
        json_attributes = create_json_attributes(@trail)
        feature = entity_factory.feature(RGeo::Geographic.spherical_factory.point(0,0), @trail.id, json_attributes)
        render json: RGeo::GeoJSON::encode(feature)
      end
    end
  end

  # # GET /trails/new
  # We're not currently allowing trails to be created from the admin UI
  #
  # def new
  #   @trail = Trail.new
  # end

  # GET /trails/1/edit
  def edit
    unless authorized?
      redirect_to trails_path, notice: 'Authorization failure.'
    end
  end

  # # POST /trails
  # # POST /trails.json
  # def create
  #   @trail = Trail.new(trail_params)

  #   respond_to do |format|
  #     if @trail.save
  #       format.html { redirect_to trails_path, notice: 'Trail was successfully created.' }
  #       format.json { render action: 'show', status: :created, location: @trail }
  #     else
  #       format.html { render action: 'new' }
  #       format.json { render json: @trail.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /trails/1
  # PATCH/PUT /trails/1.json
  def update
    respond_to do |format|
      if params[:trail][:delete_photo] && params[:trail][:delete_photo] == "1"
        @trail.photorecord_attributes = { id: params[:trail][:photorecord_attributes][:id], _destroy: 1 }
      end
      # if params[:trail][:photorecord_attributes][:id] == "" && params[:trail][:photorecord_attributes][:photo].nil?
      #   params[:trail].delete :photorecord_attributes
      # end
      if authorized? && @trail.update(trail_params)
        format.html { redirect_to trails_path, notice: 'Trail was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @trail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trails/1
  # DELETE /trails/1.json
  def destroy
    respond_to do |format|
      if authorized? && @trail.destroy
        format.html { redirect_to trails_url, notice: "Trail '" + @trail.name + "' was successfully deleted." }
        format.json { render :json => { head: no_content }, status: :ok }
      else
        format.html { redirect_to trails_url, notice: "Trail '" + @trail.name + "' was not deleted." }
        format.json { render :json => { head: no_content }, status: :unprocessable_entity }
      end
    end
  end

  # POST /trails/upload
  def upload
    if !current_user
      head 403
    end
    @confirmed = params[:confirmed] ? true : false
    redirect_to trails_url, notice: "Please enter a source organization code for uploading trail data." if params[:source_id].empty?
    source_id = params[:source_id]
    @source = Organization.find(source_id)
    parsed_trails = Trail.parse(params[:trails])
    if parsed_trails.nil?
      redirect_to trails_url, notice: "Unable to parse file #{params[:trails].original_filename}. Make sure it is a valid CSV file."
      return
    end
    source_trails = Trail.where(source: @source)
    @non_source_trails = Trail.where.not(source: @source)
    # remove all trails from the current source
    @removed_trails = []
    source_trails.each do |old_trail|
      removed_trail = Hash.new
      removed_trail[:trail] = old_trail
      if @confirmed
        removed_trail[:success] = old_trail.destroy
      else
        removed_trail[:success] = true
      end
      @removed_trails.push(removed_trail)
    end
    # add all of the new trails
    @added_trails = []
    parsed_trails.each do |new_trail|
      photorecord = Photorecord.where(source_id: new_trail.source, name: new_trail.name).first     
      if photorecord
        new_trail.photorecord = photorecord
      end
      added_trail = Hash.new
      added_trail[:trail] = new_trail
      if new_trail.source != @source
        added_trail[:success] = false
        if !new_trail.source.nil?
          added_trail[:message] = "Trail source organization #{new_trail.source.code} doesn't match user organization #{@source.code}."
        else
          added_trail[:message] = "No trail source found."
        end
      elsif @confirmed
        if (new_trail.save)
          added_trail[:success] = true
        else
          added_trail[:success] = false
          added_trail[:message] = new_trail.errors.full_messages
        end
      else 
        # we're just doing a test run, so check for validity
        if (new_trail.valid?)
          added_trail[:success] = true
        else
          # this is because we can't easily test name uniqueness without deleting data
          if new_trail.errors.full_messages == ["Name  has already been taken for this source"]
            added_trail[:success] = true
          else
            added_trail[:success] = false
            added_trail[:message] = new_trail.errors.full_messages
          end
        end
      end
      @added_trails.push(added_trail)
    end
  end

  def default_url_options
    { all: @show_all }.merge(super)
  end

  def set_show_all_param
    @show_all = params[:all] if params[:all]
  end

  def create_json_attributes(trail)
    json_attributes = trail.attributes.clone.except!("created_at", "updated_at", "source_id", "steward_id")
    if trail.source
      json_attributes["source"] = trail.source.code
      json_attributes["source_fullname"] = trail.source.full_name
      json_attributes["source_phone"] = trail.source.phone
      json_attributes["source_url"] = trail.source.url
      json_attributes["source_logo_url"] = trail.source.logo.url(:medium)
    end
    if trail.steward 
      json_attributes["steward"] = trail.steward.code
      json_attributes["steward_fullname"] = trail.steward.full_name
      json_attributes["steward_phone"] = trail.steward.phone
      json_attributes["steward_url"] = trail.steward.url
      json_attributes["steward_logo_url"] = trail.steward.logo.url(:medium)
    end
    if trail.photorecord
      json_attributes["orig_photo_url"] = trail.photorecord.photo.url
      json_attributes["medium_photo_url"] = trail.photorecord.photo.url(:medium)
      json_attributes["thumb_photo_url"] = trail.photorecord.photo.url(:thumb)
      json_attributes["photo_credit"] = trail.photorecord.credit
    end
    json_attributes
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_trail
      @trail = Trail.find(params[:id])
    end

    def authorized?
      current_user.admin? || (@trail && (current_user.organization == @trail.source)) 
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def trail_params
      params.require(:trail).permit(:name, :status, :statustext, :description, 
        :source, :source_id, :steward, :steward_id, :length, :accessible, :hike, :equestrian, :xcntryski, :dogs, 
        :roadbike, :mtnbike, :conditions, :map_url, :trlsurface, :delete_photo, :photorecord_attributes => [:photo, :source, :source_id, :name, :id, :credit])
    end


    def check_for_cancel
      if params[:commit] == "Cancel"
        redirect_to trailheads_path
      end
    end
end

app/helpers/trails_helper.rb
module TrailsHelper
  def setup_trail(trail)
    trail.build_photorecord if trail.photorecord.nil?
    trail
  end
end

app/views/trails/_form.html.erb
<%= form_for(setup_trail(@trail), html: { multipart: true }) do |f| %>
  <% if @trail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trail.errors.count, "error") %> prohibited this trail from being saved:</h2>

      <ul>
      <% @trail.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <span class='h3-Edit'><%= f.label :name %></span>
    <span class='formAnswer'><%= @trail.name %></span>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :status %></span>
    <span class='finePrint'>Note: Notices appear in yellow, and are good for displaying information about events or non-closure related notes. Closures appear in red.</span>
    <%= f.select :status, [["Open", 0], ["Notice", 1], ["Closed", 2]] %>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :statustext, "Status Description" %></span>   
    <span class='finePrint'>Note: You need to include a short description if the trail status is "Notice" or "Closed". We don't have any prepopulated messages, so your description is critical for the user to understand why an alert icon appears in a trail description. "Open" trails do not display a status description.</span>
    <%= f.text_field :statustext, size: 120 %>
  </div>
  <div class="field">
     <span class='h3-Edit'><%= f.label :description, "Trail Description" %></span>
     <span class='finePrint'>Feel free to add some basic html here to insert things like links and italics. </span>
    <%= f.text_area :description, cols: 69, rows: 5 %>
  </div>
  <div class="field">
    <%= f.fields_for :photorecord do |ff| %>
       <span class='h3-Edit'><%= ff.label :photo %></span>
       <span class='finePrint'>Note:  The app was designed for standard horizontal images. These dimensions allow people to see the photo, plus important information about the trail (length, popular activities) before scrolling. 
        <br><br>
        Accepted file types: .jpegs and .pngs</span>
      <% @trail.photorecord.photo.url %>
      <% unless @trail.photorecord.photo.url =~ /missing.png/ %>
      <%= link_to image_tag(@trail.photorecord.photo.url(:thumb)), @trail.photorecord.photo.url %>
      <% end %>
      <%= ff.file_field :photo %><br>
       <span class='h3-Edit'><%= ff.label :credit %></span>
      <%= ff.text_field :credit %><br>
      <%= ff.hidden_field :source_id, value: @trail.source_id %>
      <%= ff.hidden_field :name, value: @trail.name %>
      <%= ff.hidden_field :id, value: @trail.photorecord.id %>
    <% end %> 
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label "Delete current photo:" %></span>
    <%= f.check_box :delete_photo, { checked: 1 } %>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :source %></span>
    <span class='formAnswer'><%= @trail.source.code %></span>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :steward %></span>
    <span class='finePrint'>This is the organization trail users should contact for more information.</span>
    <%= f.select :steward_id, Organization.all.collect{ |org| [org.code, org.id]} %>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :length, "Length" %></span>
    <%= f.text_field :length, size: 3 %>
    <span class='formAnswer'>miles</span>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :accessible, "Accessible" %>:</span>
    <%= f.select :accessible, ["y", "n"], {include_blank: true} %>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :hike, "Hiking" %></span>
    <%= f.select :hike, ["y", "n"], {include_blank: true} %>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :equestrian %></span>
    <%= f.select :equestrian, ["y", "n"], {include_blank: true} %>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :xcntryski, "Cross-Country Ski" %></span>
    <%= f.select :xcntryski, ["y", "n"], {include_blank: true} %>
  </div>
  <!-- We decided not to show "dogs in detail panel, so I am hiding it here <div class="field">
    <span class='h3-Edit'><%= f.label :dogs %></span>
    <%= f.select :dogs, ["y", "n"], {include_blank: true} %>
  </div> -->
  <div class="field">
    <span class='h3-Edit'><%= f.label :roadbike, "Road Bikes" %></span>
    <%= f.select :roadbike, ["y", "n"], {include_blank: true} %>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :mtnbike, "Mountain Bikes" %></span>
    <span class='finePrint'>This field has been manually disabled in the user-facing app (the button is gray). If you select "y" get in touch with the admin so that the html/css can be updated and users can begin filtering for mountain bikes.</span>
    <%= f.select :mtnbike, ["y", "n"], {include_blank: true} %>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :conditions, "ADDITIONAL TRAIL CONDITIONS" %></span>
      <span class='finePrint'>This is extra space to describe special circumstances for the trail types (hiking, cycling, wheelchair accessibility, equestrian use, skiing, and mountain biking).</span>
    <%= f.text_area :conditions, cols: 69, rows: 5 %>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :map_url, "Map URL" %></span>
    <%= f.text_field :map_url, size: 120 %>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :trlsurface, "Trail Surface" %></span>
    <%= f.text_field :trlsurface %>
  </div>
  <div class="actions">
    <%= f.submit %>
    <%= f.submit :Cancel %>
  </div>
<% end %>

app/views/trails/edit.html.erb
<h1>Edit Trail</h1>

<div class='formContent'>
	<%= render 'form' %>
</div>

<div class='formButtons'>
	<!--back button<span class='backButton'>
		<%= link_to 'Back', trails_path %>
	</span> -->
	<span class='addNewButton'>	
		<%= link_to 'View', @trail %>
	</span>	
</div>

app/views/trails/index.html.erb
<h1>Trails</h1>
<p class='uploadDescription'>
Upload a CSV or GeoJSON (any geodata supplied will be ignored) of your current trail data to update this list (make sure it follows the <a href="https://docs.google.com/a/codeforamerica.org/document/d/1frt5HkKTdqEaNEnfk2Dq9IYxctvPjVnoU_F33Px2zSQ/edit" target="_blank">standard</a>). Note: this will replace all of your organization's existing data! Before replacing content, we recommend downloading your current data in case anything goes wrong. You can download the current trail data for <%= current_user.admin? ? "all sources" : "#{current_user.organization.code}" %> in 
    
<% if current_user.admin? %>
    <%= link_to "JSON", {action: "index", format: :json}, target: "_blank" %> or 
    <%= link_to "CSV", {action: "index", format: :csv}, target: "_blank" %>.
    <% else %>
    <%= link_to "JSON", {action: "index", source_id: current_user.organization_id, format: :json}, target: "_blank" %> or
    <%= link_to "CSV", {action: "index", source_id: current_user.organization_id, format: :csv}, target: "_blank" %>.
    <% end %>
Note: The data standard includes a field for allowing dogs on the trails, but due to feedback it has been removed from the user-facing application.
</p>
<%= form_tag({ action: :upload }, multipart: true) do %>
  <% if current_user.admin? %>
    <%= select_tag "source_id", options_from_collection_for_select(Organization.all, :id, :code) %>
  <% else %>
  <%= hidden_field_tag 'source_id', current_user.organization.id %>
  <% end %>
  <%= file_field_tag 'trails' %><br>

  <%= submit_tag "Test Upload", id: "submitData", data: { confirm: 'Are you sure? If the "Replace Existing Data" box is checked, this will replace all of your existing trail data.' } %>
  <%= label_tag :confirmed, 'Replace Existing Data' %>
  <%= check_box_tag 'confirmed', 'Confirm', false, {id: "confirmed", onclick: "if ($('#confirmed').is(':checked')) { $('#submitData').val('Upload Data') } else {  $('#submitData').val('Test Upload'); }"} %> 
<% end %>
<br>
<% if current_user.admin? %>
<p class="tableCaption">
  Showing all trails.
</p>
<% else %> 
<span class='tabLeft <%= "active" if params[:all] == "true" %>'><%= link_to "All Trails", :action => "index", :all => "true" %></span>
<% if current_user.organization %>
<span class='tabRight <%= "active" if params[:all] == "false" || params[:all].nil? %>'><%= link_to "Only #{current_user.organization.code} Trails", :action => "index", :all => "false" %></span>
<% end %>
<% end %>
<table id='trails'>
  <thead>
    <tr>
      <th>Name</th>
      <th>Status</th>
      <th>Status Text</th>
      <th>Description</th>
      <th>Source</th>
      <th>Steward</th>
      <th>Photo</th>
      <th colspan=3>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @trails.each do |trail| %>
    <tr>
      <td><%= trail.name %></td>
      <td>
        <% if trail.status == 0 %>
        Open
        <% elsif trail.status == 1 %>
        Notice
        <% elsif trail.status == 2 %>
        Closed
        <% end %>
      </td>
      <td><%= truncate(trail.statustext, length: 50) %></td>
      <td><%= truncate(trail.description, length: 50) %></td>
      <td><%= trail.source.code if trail.source %></td>
      <td><%= trail.steward.code if trail.steward %></td>
      <td>
        <%= image_tag trail.photorecord.photo.url(:thumb) unless (trail.photorecord.nil? || trail.photorecord.photo.url =~ /missing.png$/) %>
      </td>
      <% if (current_user.admin? || current_user.organization == trail.source) %>
      <td class="actions"><%= link_to 'View', trail, :class => "tableLink" %></td>
      <td class="actions"><%= link_to 'Edit', edit_trail_path(trail), :class => "tableLink" %></td>
      <td class="actions"><%= link_to 'Delete', trail, :class => "tableLink-delete", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/trails/new.html.erb
<h1>New trail</h1>

<%= render 'form' %>

<%= link_to 'Back', trails_path %>

app/views/trails/show.html.erb
<p id="notice"><%= notice %></p>

<div class='formContent-Show'>
  <h3>
    Name:
    <span class='formAnswer'><%= @trail.name %></span>
  </h3>

  <h3>
    Status:
    <span class='formAnswer'><%= @trail.status %></span>
  </h3>

  <h3>
    Status Description:
    <span class='formAnswer'><%= @trail.statustext %></span>

  <h3>
    Description:
    <span class='formAnswer'><%= @trail.description %></span>
  </h3>

  <h3>
    Photo
    <span class='formAnswer'><% if @trail.photorecord && @trail.photorecord.photo? %>
      <span class='h3-Photo'>medium</span>
      <%= image_tag @trail.photorecord.photo.url(:medium) %>
      <br><br>
      <span class='h3-Photo'>thumb</span>
      <%= image_tag @trail.photorecord.photo.url(:thumb) %>
    <% else %>
      [None]
    <% end %></span>
  </h3>

  <h3>
    Photo credit:
    <span class='formAnswer'><% if @trail.photorecord && @trail.photorecord.credit? %>
      <%= @trail.photorecord.credit %>
    <% else %>
      [None]
    <% end %></span>
  <h3>
    Source:
    <span class='formAnswer'><%= @trail.source.code %></span>
  </h3>

  <h3>
    Steward:
    <span class='formAnswer'><%= @trail.steward.code %></span>
  </h3>

  <h3>
    Length:
    <span class='formAnswer'><%= @trail.length %></span>
  </h3>

  <h3>
    Hiking:
    <span class='formAnswer'><%= @trail.hike %></span>
  </h3>

  <h3>
    Equestrian:
    <span class='formAnswer'><%= @trail.equestrian %></span>
  </h3>

  <h3>
    Cross-Country Ski:
    <span class='formAnswer'><%= @trail.xcntryski %></span>
  </h3>
<!-- We decided not to display this in trailsy
  <h3>
    Dogs:
    <span class='formAnswer'><%= @trail.dogs %></span>
  </h3> -->

  <h3>
    Road Bikes:
    <span class='formAnswer'><%= @trail.roadbike %></span>
  </h3>

  <h3>
    Mountain Bikes:
    <span class='formAnswer'><%= @trail.mtnbike %></span>
  </h3>

  <h3>
    Map url:
    <span class='formAnswer'><a href="<%= @trail.map_url %>" target="_blank"><%= @trail.map_url %></a></span>
  </h3>

  <h3>
    Surface:
    <span class='formAnswer'><%= @trail.trlsurface %></span>
  </h3>
  </div>

  <div class='formButtons'>
    <!--back button<span class='backButton'>
      <%= link_to 'Back', trails_path %>
    </span> -->
    <span class='addNewButton'>
      <%= link_to 'Edit', edit_trail_path(@trail) %>
    </span>
  </div>

app/views/trails/upload.html.erb
<h1>Upload Complete</h1>
<p>Note: See the table below for specific information regarding the upload for each trail listing.</p> 
<p>Errors are featured within the table.</p>
<!--
<%= link_to "Back to Trail Listing", trails_path %>-->
<p>
<% if @confirmed %>
  Trail data updated. Note the changes below.
<% else %>
  See your proposed changes below. Your trail data has NOT been permanently updated. To update your data, hit the "back" button on your browser and check the "Confirmed" checkbox before submitting. Note that duplicate trail names are not detected in this preview. 
<% end %>
</p>
<% if current_user.admin? %>
<p class='tableCaption'>Source matches (matching "<%= @source.code %>")</p>
<% else %>
<p class='tableCaption'>Source matches (matching "<%= current_user.organization.code %>")</p>
<% end %>
</p>
<table>
  <tr>
    <th>
      Status
    </th>
    <th>
      Trailhead Name
    </th>
    <th>
      Import errors
    </th>
  </tr>
  <% @added_trails.each do |added_trail| %>
  <tr>
    <td>
      <% if added_trail[:success] %>
      <b><%= @confirmed ? "Added" : "Would Be Added" %></b>
      <% else %>
      <b><%= @confirmed ? "Not Added" : "Would Not Be Added" %></b> 
      <% end %>
    </td>
    <td>
      <%= added_trail[:trail].name %>
    </td>
    <td>
      <%= added_trail[:message] %>
    </td>
  </tr>
  <% end %>
  <% @removed_trails.each do |removed_trail| %>
  <tr>
    <td>  
      <% if removed_trail[:success] %>
      <b><%= @confirmed ? "Deleted" : "Would Be Deleted" %></b> 
      <% else %>
      <b><%= @confirmed ? "Not Deleted" : "Would Not Be Deleted" %></b>
      <% end %>
    </td>
    <td>
      <%= removed_trail[:trail].name %>
    </td>
    <td>
      <%= removed_trail[:trail].created_at %>
    </td>
  </tr>
  <% end %>
</table>
<!-- 
<h3>Source non-matches</h3>
<table>
  <% @non_source_trails.each do |trail| %>
  <tr>
    <td>
      <%= trail.name %>
    </td>
    <td>
      <%= trail.source.code %>
    </td>
  </tr>
  <% end %>
</table>
-->