config/routes.rb
Trailsyserver::Application.routes.draw do
  resources :organizations

  devise_for :users, :controllers => { :registrations => "registrations" }
  
  scope "/admin" do
    resources :users do
      member do
        get :approve
      end
    end
  end
  
  resources :trailsegments do
    collection do
      post 'upload'
    end
  end

  resources :trailheads do
    collection do
      post 'upload'
    end
  end

  resources :trails do
    collection do
      post 'upload'
    end
  end

  get '.well-known/status' => 'status#check'

  get '/admin' => 'trails#index'
  
  root 'trails#index'

  

end

app/models/organization.rb
class Organization < ActiveRecord::Base
  has_attached_file :logo, :styles => { medium: "150x150>"}

  validates :code, uniqueness: true
  has_many :sourcetrails, class_name: "Trail", foreign_key: "source_id", dependent: :destroy
  has_many :stewardtrails, class_name: "Trail", foreign_key: "steward_id"
  has_many :users, dependent: :destroy
  has_many :sourcesegments, class_name: "Trailsegment", foreign_key: "source_id", dependent: :destroy
  has_many :stewardsegments, class_name: "Trailsegment", foreign_key: "steward_id"
  has_many :photorecords, class_name: "Photorecord", foreign_key: "source_id", dependent: :destroy
  has_many :sourcetrailheads, class_name: "Trailhead", foreign_key: "source_id", dependent: :destroy
  has_many :stewardtrailheads, class_name: "Trailhead", foreign_key: "steward_id"

  def logo_url
    @logo_url
  end

  def logo_url=(logo)
    @logo_url = logo
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_organization, only: [:show, :edit, :update, :destroy, :index]
  before_action :authorize, only: [:edit, :update, :destroy]

  # GET /organizations
  # GET /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1
  # GET /organizations/1.json
  def show
    @organization.logo_url = @organization.logo
    respond_to do |format|
      format.html
      format.json { render json: @organization, methods: [:logo_url] }
    end
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  # GET /organizations/1/edit
  def edit
  end

  # POST /organizations
  # POST /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to @organization, notice: 'Organization was successfully created.' }
        format.json { render action: 'show', status: :created, location: @organization }
      else
        format.html { render action: 'new' }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1
  # PATCH/PUT /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to @organization, notice: 'Organization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1
  # DELETE /organizations/1.json
  def destroy
    @organization.destroy
    respond_to do |format|
      format.html { redirect_to organizations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      if params[:id]
        @organization = Organization.find(params[:id])
      else
        @organization = Organization.find_by(code: current_user.organization.code) unless current_user.admin?
      end
    end

    def authorize
      unless current_user.admin? || (current_user.organization.code == @organization.code)
        redirect_to organizations_url, notice: 'Permission denied.'
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def organization_params
      params.require(:organization).permit(:code, :full_name, :phone, :url, :logo, :logo_file_name)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_for(@organization) do |f| %>
  <% if @organization.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
      <% @organization.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class='finePrint'>This is the information that appears at the bottom of each trail descprition in the application.</div>
  <br>
  <div class="field">
    <span class='h3-Edit'><%= f.label :code %></span>
    <%= f.text_field :code, size: 13 %>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :full_name %></span>
    <%= f.text_field :full_name, size: 60 %>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :phone %></span>
    <%= f.text_field :phone, size: 13 %>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :url %></span>
    <%= f.text_field :url, size: 60 %>
  </div>
  <div class="field">
    <span class='h3-Edit'><%= f.label :logo %></span>
    <div class='finePrint'>Logo files should be cropped in completely to the edge of the artwork. This way, all of the logos will have consistant margins in the footer of the app.
    <br>
    <br>
    Accepted file types: .jpeg (if the logo is on a white background) and .png</div>
    <% if @organization.logo.url =~ /missing.png/ %>
      <span class='formAnswer'>[None]</span>
    <% else %>
    <%= link_to image_tag(@organization.logo.url(:medium)) %>
    <% end %>
    <br><br>
    <%= f.file_field :logo %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/organizations/edit.html.erb
<h1>Edit Organization</h1>

<div class='formContent'>
	<%= render 'form' %>
</div>

<div class='formButtons'>
	<!--back button <span class='backButton'>
		<%= link_to 'Back', organizations_path %>
	</span> -->
	<span class='addNewButton'>	
		<%= link_to 'View', @organization %>
	</span>		
</div>

app/views/organizations/index.html.erb
<h1>Organizations</h1>
<p class='tableCaption'>
  Manage organization information here.
</p>
<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Full name</th>
      <th>Phone</th>
      <th>Url</th>
      <th colspan=2>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @organizations.each do |organization| %>
      <tr>
        <td><%= organization.code %></td>
        <td><%= organization.full_name %></td>
        <td><%= organization.phone %></td>
        <td><%= organization.url %></td>
        <% if current_user.admin? || (current_user.organization.code == organization.code) %>
          <td><%= link_to 'Edit', edit_organization_path(organization), :class => "tableLink" %></td>
          <% if current_user.admin? %>
            <td><%= link_to 'Delete', organization, :class => "tableLink-delete", method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<div class='formButtons'>
  <div class='finePrint'>When an organization is deleted, all of the users, trails, trailheads, and trailsegments associated with that organization are deleted as well, except in the case of stewards, in which case the value will be blank. Don't delete an organization unless it is absolutely necessary.</div>
  <br><br>
  <% if current_user.admin? %>
  <span class='buttonBelow'><%= link_to 'Add New Organization', new_organization_path%></span>
  <% end %>
</div>

app/views/organizations/new.html.erb
<h1>Add Organization</h1>

<div class='formContent'>
	<%= render 'form' %>
</div>
<!--back button
<div class='formButtons'>
	<span class='backButton'><%= link_to 'Back', organizations_path %></span>
</div> -->

app/views/organizations/show.html.erb
<p id="notice"><%= notice %></p>

<div class='formContent-Show'>
  <h3>
    Code:
    <span class='formAnswer'><%= @organization.code %></span>
  </h3>

  <h3>
    Full name:
    <span class='formAnswer'><%= @organization.full_name %></span>
  </h3>

  <h3>
    Phone:
    <span class='formAnswer'><%= @organization.phone %></span>
  </h3>

  <h3>
    Url:
    <span class='formAnswer'><%= @organization.url %></span>
  </h3>

  <h3>
    Logo:
    <% if @organization.logo %>
      <span class='formAnswer'><%= image_tag @organization.logo.url %></span>
    <% else %>
      [None]
    <% end %>
  </h3>
</div>

<div class='formButtons'>
  <!--back button <span class='backButton'>  
    <%= link_to 'Back', organizations_path %>
  </span> -->
  <span class='addNewButton'>
    <%= link_to 'Edit', edit_organization_path(@organization) %>
  </span>    
</div>