config/routes.rb
Trailsyserver::Application.routes.draw do
  resources :organizations

  devise_for :users, :controllers => { :registrations => "registrations" }
  
  scope "/admin" do
    resources :users do
      member do
        get :approve
      end
    end
  end
  
  resources :trailsegments do
    collection do
      post 'upload'
    end
  end

  resources :trailheads do
    collection do
      post 'upload'
    end
  end

  resources :trails do
    collection do
      post 'upload'
    end
  end

  get '.well-known/status' => 'status#check'

  get '/admin' => 'trails#index'
  
  root 'trails#index'

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>To The Trails Administration</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'favicon.ico' %>
</head>
<body>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
  <div class="topheader">
    <ul class="hmenu"> 
      <%= image_tag "LogoBigger.png", class: "admin-logo", alt: "Product1" %>
      <%= render 'devise/menu/registration_items'%>
      <%= render 'devise/menu/login_items' %>
    </ul>
  </div>
  <div id="MenuBar">

    <ul >
      <li class="<%= 'active' if current_page?(controller: '/trails') %>"><%= link_to "Trails", trails_path, :class => "MenuItem" %></li>
      <li class="<%= 'active' if current_page?(controller: '/trailheads') %>"><%= link_to "Trailheads", trailheads_path, :class => "MenuItem" %></li>
      <li class="<%= 'active' if current_page?(controller: '/trailsegments') %>"><%= link_to "Segments", trailsegments_path, :class => "MenuItem" %></li>
      <li class="<%= 'active' if current_page?(controller: '/organizations') %>"><%= link_to "Organizations", organizations_path, :class => "MenuItem" %></li>
      <% if current_user && current_user.admin? %>
        <li class="<%= 'active' if current_page?(controller: '/users') %>"><%= link_to "Users", users_path, :class => "MenuItem" %></li>
      <% end %>
    </ul>
  </div>
<%= yield %>
</body>
</html>